###################################################################

# Created by write_sdc on Tue Apr 14 23:12:08 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_wire_load_mode top
set_wire_load_model -name ForQA -library saed32rvt_ff1p16v125c
set_load -pin_load 0.05 [get_ports uart_txd]
set_load -pin_load 0.05 [get_ports done]
set_load -pin_load 0.05 [get_ports pass]
set_case_analysis 0 [get_ports test_mode]
set_case_analysis 0 [get_ports scan_en]
create_clock [get_ports ref_clk]  -period 7.5  -waveform {0 3.75}
set_clock_uncertainty -setup 0.16  [get_clocks ref_clk]
set_clock_uncertainty -hold 0.04  [get_clocks ref_clk]
create_generated_clock [get_pins u_pll/CLK_4X]  -name clk_fast  -source [get_pins u_pll/REF_CLK]  -multiply_by 4
set_clock_uncertainty -setup 0.04  [get_clocks clk_fast]
set_clock_uncertainty -hold 0.01  [get_clocks clk_fast]
create_generated_clock [get_pins u_pll/CLK_2X]  -name clk_div2  -source [get_pins u_pll/REF_CLK]  -multiply_by 2
set_clock_uncertainty -setup 0.08  [get_clocks clk_div2]
set_clock_uncertainty -hold 0.02  [get_clocks clk_div2]
create_generated_clock [get_pins u_pll/CLK_1X]  -name clk_div4  -source [get_pins u_pll/REF_CLK]  -multiply_by 1
set_clock_uncertainty -setup 0.16  [get_clocks clk_div4]
set_clock_uncertainty -hold 0.04  [get_clocks clk_div4]
create_generated_clock [get_pins u_div8/clk_out]  -name clk_div8  -source [get_pins u_div8/clk_in]  -divide_by 2
set_clock_uncertainty -setup 0.32  [get_clocks clk_div8]
set_clock_uncertainty -hold 0.08  [get_clocks clk_div8]
group_path -name INS  -from [list [get_ports ref_clk] [get_ports rst_n] [get_ports start]           \
[get_ports uart_rxd] [get_ports {aes_key_ext[127]}] [get_ports                 \
{aes_key_ext[126]}] [get_ports {aes_key_ext[125]}] [get_ports                  \
{aes_key_ext[124]}] [get_ports {aes_key_ext[123]}] [get_ports                  \
{aes_key_ext[122]}] [get_ports {aes_key_ext[121]}] [get_ports                  \
{aes_key_ext[120]}] [get_ports {aes_key_ext[119]}] [get_ports                  \
{aes_key_ext[118]}] [get_ports {aes_key_ext[117]}] [get_ports                  \
{aes_key_ext[116]}] [get_ports {aes_key_ext[115]}] [get_ports                  \
{aes_key_ext[114]}] [get_ports {aes_key_ext[113]}] [get_ports                  \
{aes_key_ext[112]}] [get_ports {aes_key_ext[111]}] [get_ports                  \
{aes_key_ext[110]}] [get_ports {aes_key_ext[109]}] [get_ports                  \
{aes_key_ext[108]}] [get_ports {aes_key_ext[107]}] [get_ports                  \
{aes_key_ext[106]}] [get_ports {aes_key_ext[105]}] [get_ports                  \
{aes_key_ext[104]}] [get_ports {aes_key_ext[103]}] [get_ports                  \
{aes_key_ext[102]}] [get_ports {aes_key_ext[101]}] [get_ports                  \
{aes_key_ext[100]}] [get_ports {aes_key_ext[99]}] [get_ports                   \
{aes_key_ext[98]}] [get_ports {aes_key_ext[97]}] [get_ports {aes_key_ext[96]}] \
[get_ports {aes_key_ext[95]}] [get_ports {aes_key_ext[94]}] [get_ports         \
{aes_key_ext[93]}] [get_ports {aes_key_ext[92]}] [get_ports {aes_key_ext[91]}] \
[get_ports {aes_key_ext[90]}] [get_ports {aes_key_ext[89]}] [get_ports         \
{aes_key_ext[88]}] [get_ports {aes_key_ext[87]}] [get_ports {aes_key_ext[86]}] \
[get_ports {aes_key_ext[85]}] [get_ports {aes_key_ext[84]}] [get_ports         \
{aes_key_ext[83]}] [get_ports {aes_key_ext[82]}] [get_ports {aes_key_ext[81]}] \
[get_ports {aes_key_ext[80]}] [get_ports {aes_key_ext[79]}] [get_ports         \
{aes_key_ext[78]}] [get_ports {aes_key_ext[77]}] [get_ports {aes_key_ext[76]}] \
[get_ports {aes_key_ext[75]}] [get_ports {aes_key_ext[74]}] [get_ports         \
{aes_key_ext[73]}] [get_ports {aes_key_ext[72]}] [get_ports {aes_key_ext[71]}] \
[get_ports {aes_key_ext[70]}] [get_ports {aes_key_ext[69]}] [get_ports         \
{aes_key_ext[68]}] [get_ports {aes_key_ext[67]}] [get_ports {aes_key_ext[66]}] \
[get_ports {aes_key_ext[65]}] [get_ports {aes_key_ext[64]}] [get_ports         \
{aes_key_ext[63]}] [get_ports {aes_key_ext[62]}] [get_ports {aes_key_ext[61]}] \
[get_ports {aes_key_ext[60]}] [get_ports {aes_key_ext[59]}] [get_ports         \
{aes_key_ext[58]}] [get_ports {aes_key_ext[57]}] [get_ports {aes_key_ext[56]}] \
[get_ports {aes_key_ext[55]}] [get_ports {aes_key_ext[54]}] [get_ports         \
{aes_key_ext[53]}] [get_ports {aes_key_ext[52]}] [get_ports {aes_key_ext[51]}] \
[get_ports {aes_key_ext[50]}] [get_ports {aes_key_ext[49]}] [get_ports         \
{aes_key_ext[48]}] [get_ports {aes_key_ext[47]}] [get_ports {aes_key_ext[46]}] \
[get_ports {aes_key_ext[45]}] [get_ports {aes_key_ext[44]}] [get_ports         \
{aes_key_ext[43]}] [get_ports {aes_key_ext[42]}] [get_ports {aes_key_ext[41]}] \
[get_ports {aes_key_ext[40]}] [get_ports {aes_key_ext[39]}] [get_ports         \
{aes_key_ext[38]}] [get_ports {aes_key_ext[37]}] [get_ports {aes_key_ext[36]}] \
[get_ports {aes_key_ext[35]}] [get_ports {aes_key_ext[34]}] [get_ports         \
{aes_key_ext[33]}] [get_ports {aes_key_ext[32]}] [get_ports {aes_key_ext[31]}] \
[get_ports {aes_key_ext[30]}] [get_ports {aes_key_ext[29]}] [get_ports         \
{aes_key_ext[28]}] [get_ports {aes_key_ext[27]}] [get_ports {aes_key_ext[26]}] \
[get_ports {aes_key_ext[25]}] [get_ports {aes_key_ext[24]}] [get_ports         \
{aes_key_ext[23]}] [get_ports {aes_key_ext[22]}] [get_ports {aes_key_ext[21]}] \
[get_ports {aes_key_ext[20]}] [get_ports {aes_key_ext[19]}] [get_ports         \
{aes_key_ext[18]}] [get_ports {aes_key_ext[17]}] [get_ports {aes_key_ext[16]}] \
[get_ports {aes_key_ext[15]}] [get_ports {aes_key_ext[14]}] [get_ports         \
{aes_key_ext[13]}] [get_ports {aes_key_ext[12]}] [get_ports {aes_key_ext[11]}] \
[get_ports {aes_key_ext[10]}] [get_ports {aes_key_ext[9]}] [get_ports          \
{aes_key_ext[8]}] [get_ports {aes_key_ext[7]}] [get_ports {aes_key_ext[6]}]    \
[get_ports {aes_key_ext[5]}] [get_ports {aes_key_ext[4]}] [get_ports           \
{aes_key_ext[3]}] [get_ports {aes_key_ext[2]}] [get_ports {aes_key_ext[1]}]    \
[get_ports {aes_key_ext[0]}] [get_ports {aes_pt_ext[127]}] [get_ports          \
{aes_pt_ext[126]}] [get_ports {aes_pt_ext[125]}] [get_ports {aes_pt_ext[124]}] \
[get_ports {aes_pt_ext[123]}] [get_ports {aes_pt_ext[122]}] [get_ports         \
{aes_pt_ext[121]}] [get_ports {aes_pt_ext[120]}] [get_ports {aes_pt_ext[119]}] \
[get_ports {aes_pt_ext[118]}] [get_ports {aes_pt_ext[117]}] [get_ports         \
{aes_pt_ext[116]}] [get_ports {aes_pt_ext[115]}] [get_ports {aes_pt_ext[114]}] \
[get_ports {aes_pt_ext[113]}] [get_ports {aes_pt_ext[112]}] [get_ports         \
{aes_pt_ext[111]}] [get_ports {aes_pt_ext[110]}] [get_ports {aes_pt_ext[109]}] \
[get_ports {aes_pt_ext[108]}] [get_ports {aes_pt_ext[107]}] [get_ports         \
{aes_pt_ext[106]}] [get_ports {aes_pt_ext[105]}] [get_ports {aes_pt_ext[104]}] \
[get_ports {aes_pt_ext[103]}] [get_ports {aes_pt_ext[102]}] [get_ports         \
{aes_pt_ext[101]}] [get_ports {aes_pt_ext[100]}] [get_ports {aes_pt_ext[99]}]  \
[get_ports {aes_pt_ext[98]}] [get_ports {aes_pt_ext[97]}] [get_ports           \
{aes_pt_ext[96]}] [get_ports {aes_pt_ext[95]}] [get_ports {aes_pt_ext[94]}]    \
[get_ports {aes_pt_ext[93]}] [get_ports {aes_pt_ext[92]}] [get_ports           \
{aes_pt_ext[91]}] [get_ports {aes_pt_ext[90]}] [get_ports {aes_pt_ext[89]}]    \
[get_ports {aes_pt_ext[88]}] [get_ports {aes_pt_ext[87]}] [get_ports           \
{aes_pt_ext[86]}] [get_ports {aes_pt_ext[85]}] [get_ports {aes_pt_ext[84]}]    \
[get_ports {aes_pt_ext[83]}] [get_ports {aes_pt_ext[82]}] [get_ports           \
{aes_pt_ext[81]}] [get_ports {aes_pt_ext[80]}] [get_ports {aes_pt_ext[79]}]    \
[get_ports {aes_pt_ext[78]}] [get_ports {aes_pt_ext[77]}] [get_ports           \
{aes_pt_ext[76]}] [get_ports {aes_pt_ext[75]}] [get_ports {aes_pt_ext[74]}]    \
[get_ports {aes_pt_ext[73]}] [get_ports {aes_pt_ext[72]}] [get_ports           \
{aes_pt_ext[71]}] [get_ports {aes_pt_ext[70]}] [get_ports {aes_pt_ext[69]}]    \
[get_ports {aes_pt_ext[68]}] [get_ports {aes_pt_ext[67]}] [get_ports           \
{aes_pt_ext[66]}] [get_ports {aes_pt_ext[65]}] [get_ports {aes_pt_ext[64]}]    \
[get_ports {aes_pt_ext[63]}] [get_ports {aes_pt_ext[62]}] [get_ports           \
{aes_pt_ext[61]}] [get_ports {aes_pt_ext[60]}] [get_ports {aes_pt_ext[59]}]    \
[get_ports {aes_pt_ext[58]}] [get_ports {aes_pt_ext[57]}] [get_ports           \
{aes_pt_ext[56]}] [get_ports {aes_pt_ext[55]}] [get_ports {aes_pt_ext[54]}]    \
[get_ports {aes_pt_ext[53]}] [get_ports {aes_pt_ext[52]}] [get_ports           \
{aes_pt_ext[51]}] [get_ports {aes_pt_ext[50]}] [get_ports {aes_pt_ext[49]}]    \
[get_ports {aes_pt_ext[48]}] [get_ports {aes_pt_ext[47]}] [get_ports           \
{aes_pt_ext[46]}] [get_ports {aes_pt_ext[45]}] [get_ports {aes_pt_ext[44]}]    \
[get_ports {aes_pt_ext[43]}] [get_ports {aes_pt_ext[42]}] [get_ports           \
{aes_pt_ext[41]}] [get_ports {aes_pt_ext[40]}] [get_ports {aes_pt_ext[39]}]    \
[get_ports {aes_pt_ext[38]}] [get_ports {aes_pt_ext[37]}] [get_ports           \
{aes_pt_ext[36]}] [get_ports {aes_pt_ext[35]}] [get_ports {aes_pt_ext[34]}]    \
[get_ports {aes_pt_ext[33]}] [get_ports {aes_pt_ext[32]}] [get_ports           \
{aes_pt_ext[31]}] [get_ports {aes_pt_ext[30]}] [get_ports {aes_pt_ext[29]}]    \
[get_ports {aes_pt_ext[28]}] [get_ports {aes_pt_ext[27]}] [get_ports           \
{aes_pt_ext[26]}] [get_ports {aes_pt_ext[25]}] [get_ports {aes_pt_ext[24]}]    \
[get_ports {aes_pt_ext[23]}] [get_ports {aes_pt_ext[22]}] [get_ports           \
{aes_pt_ext[21]}] [get_ports {aes_pt_ext[20]}] [get_ports {aes_pt_ext[19]}]    \
[get_ports {aes_pt_ext[18]}] [get_ports {aes_pt_ext[17]}] [get_ports           \
{aes_pt_ext[16]}] [get_ports {aes_pt_ext[15]}] [get_ports {aes_pt_ext[14]}]    \
[get_ports {aes_pt_ext[13]}] [get_ports {aes_pt_ext[12]}] [get_ports           \
{aes_pt_ext[11]}] [get_ports {aes_pt_ext[10]}] [get_ports {aes_pt_ext[9]}]     \
[get_ports {aes_pt_ext[8]}] [get_ports {aes_pt_ext[7]}] [get_ports             \
{aes_pt_ext[6]}] [get_ports {aes_pt_ext[5]}] [get_ports {aes_pt_ext[4]}]       \
[get_ports {aes_pt_ext[3]}] [get_ports {aes_pt_ext[2]}] [get_ports             \
{aes_pt_ext[1]}] [get_ports {aes_pt_ext[0]}] [get_ports aes_vec_valid]         \
[get_ports test_mode] [get_ports scan_en] [get_ports scan_in]]
group_path -name OUTS  -to [list [get_ports clk_fast] [get_ports clk_div2] [get_ports clk_div4]      \
[get_ports clk_div8] [get_ports scan_out] [get_ports uart_txd] [get_ports      \
done] [get_ports pass]]
set_input_delay -clock ref_clk  -max 1  [get_ports start]
set_input_delay -clock ref_clk  -min 0.2  [get_ports start]
set_input_delay -clock ref_clk  -max 1  [get_ports uart_rxd]
set_input_delay -clock ref_clk  -min 0.2  [get_ports uart_rxd]
set_input_delay -clock ref_clk  -max 1  [get_ports aes_vec_valid]
set_input_delay -clock ref_clk  -min 0.2  [get_ports aes_vec_valid]
set_output_delay -clock ref_clk  -max 1  [get_ports uart_txd]
set_output_delay -clock ref_clk  -min 0.2  [get_ports uart_txd]
set_output_delay -clock ref_clk  -max 1  [get_ports done]
set_output_delay -clock ref_clk  -min 0.2  [get_ports done]
set_output_delay -clock ref_clk  -max 1  [get_ports pass]
set_output_delay -clock ref_clk  -min 0.2  [get_ports pass]
set_input_transition -max 0.1  [get_ports rst_n]
set_input_transition -min 0.1  [get_ports rst_n]
set_input_transition -max 0.1  [get_ports start]
set_input_transition -min 0.1  [get_ports start]
set_input_transition -max 0.1  [get_ports uart_rxd]
set_input_transition -min 0.1  [get_ports uart_rxd]
set_input_transition -max 0.1  [get_ports {aes_key_ext[127]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[127]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[126]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[126]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[125]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[125]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[124]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[124]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[123]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[123]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[122]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[122]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[121]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[121]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[120]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[120]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[119]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[119]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[118]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[118]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[117]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[117]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[116]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[116]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[115]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[115]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[114]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[114]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[113]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[113]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[112]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[112]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[111]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[111]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[110]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[110]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[109]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[109]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[108]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[108]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[107]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[107]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[106]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[106]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[105]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[105]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[104]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[104]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[103]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[103]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[102]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[102]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[101]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[101]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[100]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[100]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[99]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[99]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[98]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[98]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[97]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[97]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[96]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[96]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[95]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[95]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[94]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[94]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[93]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[93]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[92]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[92]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[91]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[91]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[90]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[90]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[89]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[89]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[88]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[88]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[87]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[87]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[86]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[86]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[85]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[85]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[84]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[84]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[83]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[83]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[82]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[82]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[81]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[81]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[80]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[80]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[79]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[79]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[78]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[78]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[77]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[77]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[76]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[76]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[75]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[75]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[74]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[74]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[73]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[73]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[72]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[72]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[71]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[71]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[70]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[70]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[69]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[69]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[68]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[68]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[67]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[67]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[66]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[66]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[65]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[65]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[64]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[64]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[63]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[63]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[62]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[62]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[61]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[61]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[60]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[60]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[59]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[59]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[58]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[58]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[57]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[57]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[56]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[56]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[55]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[55]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[54]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[54]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[53]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[53]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[52]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[52]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[51]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[51]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[50]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[50]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[49]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[49]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[48]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[48]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[47]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[47]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[46]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[46]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[45]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[45]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[44]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[44]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[43]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[43]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[42]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[42]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[41]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[41]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[40]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[40]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[39]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[39]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[38]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[38]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[37]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[37]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[36]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[36]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[35]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[35]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[34]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[34]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[33]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[33]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[32]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[32]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[31]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[31]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[30]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[30]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[29]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[29]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[28]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[28]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[27]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[27]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[26]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[26]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[25]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[25]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[24]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[24]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[23]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[23]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[22]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[22]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[21]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[21]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[20]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[20]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[19]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[19]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[18]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[18]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[17]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[17]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[16]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[16]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[15]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[15]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[14]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[14]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[13]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[13]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[12]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[12]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[11]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[11]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[10]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[10]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[9]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[9]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[8]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[8]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[7]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[7]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[6]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[6]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[5]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[5]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[4]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[4]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[3]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[3]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[2]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[2]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[1]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[1]}]
set_input_transition -max 0.1  [get_ports {aes_key_ext[0]}]
set_input_transition -min 0.1  [get_ports {aes_key_ext[0]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[127]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[127]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[126]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[126]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[125]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[125]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[124]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[124]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[123]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[123]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[122]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[122]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[121]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[121]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[120]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[120]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[119]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[119]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[118]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[118]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[117]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[117]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[116]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[116]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[115]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[115]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[114]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[114]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[113]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[113]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[112]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[112]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[111]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[111]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[110]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[110]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[109]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[109]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[108]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[108]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[107]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[107]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[106]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[106]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[105]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[105]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[104]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[104]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[103]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[103]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[102]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[102]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[101]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[101]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[100]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[100]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[99]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[99]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[98]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[98]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[97]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[97]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[96]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[96]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[95]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[95]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[94]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[94]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[93]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[93]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[92]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[92]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[91]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[91]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[90]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[90]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[89]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[89]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[88]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[88]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[87]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[87]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[86]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[86]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[85]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[85]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[84]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[84]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[83]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[83]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[82]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[82]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[81]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[81]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[80]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[80]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[79]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[79]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[78]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[78]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[77]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[77]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[76]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[76]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[75]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[75]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[74]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[74]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[73]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[73]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[72]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[72]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[71]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[71]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[70]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[70]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[69]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[69]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[68]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[68]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[67]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[67]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[66]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[66]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[65]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[65]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[64]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[64]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[63]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[63]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[62]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[62]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[61]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[61]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[60]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[60]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[59]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[59]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[58]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[58]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[57]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[57]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[56]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[56]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[55]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[55]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[54]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[54]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[53]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[53]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[52]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[52]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[51]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[51]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[50]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[50]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[49]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[49]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[48]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[48]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[47]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[47]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[46]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[46]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[45]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[45]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[44]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[44]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[43]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[43]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[42]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[42]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[41]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[41]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[40]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[40]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[39]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[39]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[38]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[38]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[37]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[37]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[36]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[36]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[35]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[35]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[34]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[34]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[33]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[33]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[32]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[32]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[31]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[31]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[30]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[30]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[29]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[29]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[28]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[28]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[27]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[27]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[26]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[26]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[25]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[25]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[24]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[24]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[23]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[23]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[22]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[22]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[21]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[21]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[20]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[20]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[19]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[19]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[18]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[18]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[17]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[17]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[16]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[16]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[15]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[15]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[14]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[14]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[13]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[13]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[12]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[12]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[11]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[11]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[10]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[10]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[9]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[9]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[8]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[8]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[7]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[7]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[6]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[6]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[5]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[5]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[4]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[4]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[3]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[3]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[2]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[2]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[1]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[1]}]
set_input_transition -max 0.1  [get_ports {aes_pt_ext[0]}]
set_input_transition -min 0.1  [get_ports {aes_pt_ext[0]}]
set_input_transition -max 0.1  [get_ports aes_vec_valid]
set_input_transition -min 0.1  [get_ports aes_vec_valid]
set_input_transition -max 0.1  [get_ports test_mode]
set_input_transition -min 0.1  [get_ports test_mode]
set_input_transition -max 0.1  [get_ports scan_en]
set_input_transition -min 0.1  [get_ports scan_en]
set_input_transition -max 0.1  [get_ports scan_in]
set_input_transition -min 0.1  [get_ports scan_in]
set_false_path   -to [list [get_ports clk_fast] [get_ports clk_div2] [get_ports clk_div4]      \
[get_ports clk_div8] [get_ports scan_out]]
