1_input/model/saed32sram.v
../0_rtl/aes128_core.v
../0_rtl/aes128_core_rewrite.v
../0_rtl/cdc_toggle_sync.v
../0_rtl/clk_div2_toggle.v
../0_rtl/crc32_byte.v
../0_rtl/icg_latch.v
../0_rtl/PLL_bb_for_syn.v
../0_rtl/soc_ctrl_multiclk_soc.v
../0_rtl/sram_wrap_1rw1024x8.v
../0_rtl/top_mcu_pll_sram_multiclk_soc.v
../0_rtl/uart_rx.v
../0_rtl/uart_tx.v
1_input/tb/top_mcu_pll_sram_multiclk_soc_tbwrap.sv
1_input/tb/tb_top_mcu_pll_sram_multiclk_soc.sv
